INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(10001, CURRENT_DATE(), 'JUNSU');

INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(10002, CURRENT_DATE(), 'SEHEE');

INSERT INTO USER_DETAILS(ID, BIRTH_DATE, NAME)
VALUES(10003, CURRENT_DATE(), 'KIKI');