INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10001,'junsu', 'Get Aws Cerified',CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10002,'junsu', 'Learn Python',CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10003,'junsu', 'Learn BigData',CURRENT_DATE(), false);
